s

diff --git a/bin/s b/bin/s
--- a/bin/s
+++ b/bin/s
@@ -163,7 +163,7 @@ if [[ $verbose -eq 1 ]]; then
   echo "tldrUpdate: $tldrUpdate"
 fi
 
-gopass sync || echo "(gopass sync failed)"
+ping -q -c1 -W1 md && gopass sync || echo "(gopass sync failed)"
 
 # cache sudo
 sudo echo || exit 202
